[theme]
background = "transparent"
primary = "#DCD7BA"
secondary = "light black"
title = "#8992a7"
playing = "#DCD7BA"
playing_selected = "#D0B3FA"
playing_bg = "black"
highlight = "#c8c093"
highlight_bg = "#658594"
error = "#f8f8f2"
error_bg = "#ff5555"
statusbar = "#DCD7BA"
statusbar_progress = "#DCD7BA"
statusbar_bg = "#1F1F28"
cmdline = "#f8f8f2"
cmdline_bg = "black"
search_match = "#ff79c6"
